# Generated by Django 2.2.5 on 2020-04-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carona', '0002_auto_20200417_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='confir',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
