# Generated by Django 2.2.5 on 2020-04-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carona', '0003_custom_user_confir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='confir',
        ),
    ]
