# Generated by Django 2.2.5 on 2020-04-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carona', '0004_remove_custom_user_confir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.TextField(max_length=100)),
                ('destino', models.TextField(max_length=100)),
                ('data', models.DateField()),
                ('num_passageiros', models.IntegerField()),
                ('preco', models.FloatField()),
                ('hora_saida', models.TimeField()),
                ('hora_chegada', models.TimeField()),
            ],
        ),
    ]
