# Generated by Django 2.2.5 on 2020-05-05 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carona', '0005_carona'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='telefone',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.TextField(max_length=100)),
                ('ano', models.IntegerField(max_length=100)),
                ('imagem_carro', models.ImageField(blank=True, null=True, upload_to='media2/%Y/%m/%d/')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
