# Generated by Django 2.2.5 on 2020-05-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carona', '0008_passageiros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carona',
            name='id',
        ),
        migrations.AddField(
            model_name='carona',
            name='id_carona',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
