# Generated by Django 2.2.5 on 2020-05-10 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carona', '0009_auto_20200506_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carona',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='carona',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carona.Custom_user'),
            preserve_default=False,
        ),
    ]
